name: CScraft
main: cc.isotopestudio.cscraft.CScraft

author: Mars
description: CScraft
website: http://isotopestudio.cc
version: 1.0.0
commands:
  csclass:
    description: CScraft
    usage: /<command>
  csroom:
    description: CScraft
    usage: /<command>
  cs:
    description: CScraft
    usage: /<command>
    aliases: [csjoin, crackshot]
  csreload:
    description: CScraft
    usage: /<command>